export const FEATURED_SHOWS = [
  {
    id: 'jre',
    title: 'Joe Rogan Experience',
    shortTitle: 'JRE',
    host: 'Joe Rogan',
    query: 'Joe Rogan Experience',
    channelId: 'UCzQUP1qoWDoEbmsQxvdjxgQ',
    logo: require('../../assets/images/JRE.jpg'),
    poster: require('../../assets/images/joeroganposter.jpg'),
    stats: [
      'Overall Content: 5/5',
      'Humor: 4/5',
      'Conversational Ability: 5/5',
      'Knowledge: 3/5',
      'Production Value: 5/5',
      'Guest Clout: 5/5',
      'Interviewing: 5/5',
    ],
    bio: 'Joe Rogan is a comedian, commentator, and long-form podcast host known for broad conversations across comedy, science, culture, and current events.',
    sponsors: ['Sponsor 1', 'Sponsor 2'],
    tours: ['March 2026 - New York City', 'April 2026 - Los Angeles'],
  },
  {
    id: 'badfriends',
    title: 'Bad Friends',
    shortTitle: 'Bad Friends',
    host: 'Bobby Lee and Andrew Santino',
    query: 'Bad Friends podcast',
    channelId: 'UCi-3cgCozyRr_jMfa3fc_Lw',
    logo: require('../../assets/images/BadFriends.jpg'),
    poster: require('../../assets/images/badfriendsposter.jpg'),
    stats: [
      'Overall Content: 4/5',
      'Humor: 5/5',
      'Conversational Ability: 4/5',
      'Knowledge: 3/5',
      'Production Value: 4/5',
      'Guest Clout: 3/5',
      'Interviewing: 4/5',
    ],
    bio: 'Bad Friends mixes absurd stories, riffing, and stand-up chemistry from Bobby Lee and Andrew Santino.',
    sponsors: ['Sponsor 1', 'Sponsor 2'],
    tours: ['February 2026 - Los Angeles', 'March 2026 - New York City'],
  },
  {
    id: 'mattshane',
    title: "Matt and Shane's Secret Podcast",
    shortTitle: "Matt & Shane's",
    host: 'Matt McCusker and Shane Gillis',
    query: "Matt and Shane's Secret Podcast",
    channelId: 'UC4fZeoNxAXfbIpT3swsVh9w',
    logo: require('../../assets/images/MattShane.jpg'),
    poster: require('../../assets/images/MattandShaneposter.jpg'),
    stats: [
      'Overall Content: 3.5/5',
      'Humor: 5/5',
      'Conversational Ability: 3/5',
      'Knowledge: 4/5',
      'Production Value: 4/5',
      'Guest Clout: 2/5',
      'Interviewing: 4/5',
    ],
    bio: 'Matt and Shane deliver high-energy comedy conversations with recurring bits, guests, and long-form tangents.',
    sponsors: ['Sponsor 1', 'Sponsor 2'],
    tours: ['March 2026 - Austin', 'April 2026 - Chicago'],
  },
  {
    id: 'killtony',
    title: 'Kill Tony',
    shortTitle: 'Kill Tony',
    host: 'Tony Hinchcliffe',
    query: 'Kill Tony podcast',
    channelId: 'UCrMTGv7Xv3A3ODYIUBlrH9g',
    logo: require('../../assets/images/KillTony.jpg'),
    poster: require('../../assets/images/KillTonyposter.jpg'),
    stats: [
      'Overall Content: 4.5/5',
      'Humor: 5/5',
      'Conversational Ability: 5/5',
      'Knowledge: 5/5',
      'Production Value: 3/5',
      'Guest Clout: 4/5',
      'Interviewing: 4/5',
    ],
    bio: 'Kill Tony combines live stand-up sets, improvisation, and guest commentary with a fast-paced comedy format.',
    sponsors: ['Sponsor 1', 'Sponsor 2'],
    tours: ['March 2026 - New York City', 'April 2026 - Los Angeles'],
  },
  {
    id: 'theovon',
    title: 'This Past Weekend',
    shortTitle: 'Theo Von',
    host: 'Theo Von',
    query: 'This Past Weekend Theo Von',
    channelId: 'UCiEKV_MOhwZ7OEcgFyLKilw',
    logo: require('../../assets/images/Theo.jpg'),
    poster: require('../../assets/images/thispastweekendposter.jpg'),
    stats: [
      'Overall Content: 3/5',
      'Humor: 5/5',
      'Conversational Ability: 4/5',
      'Knowledge: 1/5',
      'Production Value: 4/5',
      'Guest Clout: 5/5',
      'Interviewing: 2/5',
    ],
    bio: 'Theo Von mixes solo storytelling and guest interviews with a distinct comedic style and conversational format.',
    sponsors: ['Sponsor 1', 'Sponsor 2'],
    tours: ['February 2026 - Nashville', 'March 2026 - New York City'],
  },
  {
    id: 'stavvy',
    title: "Stavvy's World",
    shortTitle: "Stavvy's World",
    host: 'Stavros Halkias',
    query: "Stavvy's World podcast",
    channelId: 'UCBVAaHkKSwfzee79b7SPyPw',
    logo: require('../../assets/images/Stavvy.jpg'),
    poster: require('../../assets/images/stavvysworldposter.jpg'),
    stats: [
      'Overall Content: 4.5/5',
      'Humor: 4/5',
      'Conversational Ability: 5/5',
      'Knowledge: 4/5',
      'Production Value: 3/5',
      'Guest Clout: 5/5',
      'Interviewing: 4.5/5',
    ],
    bio: 'Stavvy hosts comedy-driven interviews and episodes that blend stand-up perspective with audience interaction.',
    sponsors: ['Sponsor 1', 'Sponsor 2'],
    tours: ['March 2026 - New York City', 'April 2026 - Los Angeles'],
  },
];

export const FEATURED_SHOW_MAP = Object.fromEntries(FEATURED_SHOWS.map((show) => [show.id, show]));